name: Update all Node.js Modules

on:
  push:
  schedule:
    - cron: "0 10 * * */3"
  
jobs:
 update_nativefier:
    runs-on: windows-latest
    steps:   
     - uses: actions/checkout@v2
     - name: Create report file
       run: date +%s > report.txt
       
     - name: Update/Install Nativefier
       run: npm install nativefier
  build:
    needs: update_nativefier
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v2
     - name: Create report file
       run: date +%s > report.txt
       
     - name: Build Electron App With Nativefier
       
     - name: Commit report
       run: |
          git config --global user.name '${{ secrets.git_username }}'
          git config --global user.email '${{ secrets.git_email }}'
          git add -A
          git commit -am "Build New Version For Electron App"
          git push origin ${{ github.GITHUB_REF_NAME }}
